/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as CategoryCategoryBrandBrandRouteImport } from './routes/category_.$category.brand.$brand'
import { Route as CategoryCategoryBrandBrandItemItemidRouteImport } from './routes/category_/$category/brand_/$brand/item/$itemid'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryBrandBrandRoute =
  CategoryCategoryBrandBrandRouteImport.update({
    id: '/category_/$category/brand/$brand',
    path: '/category/$category/brand/$brand',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryCategoryBrandBrandItemItemidRoute =
  CategoryCategoryBrandBrandItemItemidRouteImport.update({
    id: '/category_/$category/brand_/$brand/item/$itemid',
    path: '/category/$category/brand/$brand/item/$itemid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/category/$category/brand/$brand': typeof CategoryCategoryBrandBrandRoute
  '/category/$category/brand/$brand/item/$itemid': typeof CategoryCategoryBrandBrandItemItemidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/category/$category/brand/$brand': typeof CategoryCategoryBrandBrandRoute
  '/category/$category/brand/$brand/item/$itemid': typeof CategoryCategoryBrandBrandItemItemidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/category_/$category/brand/$brand': typeof CategoryCategoryBrandBrandRoute
  '/category_/$category/brand_/$brand/item/$itemid': typeof CategoryCategoryBrandBrandItemItemidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/category/$category'
    | '/category/$category/brand/$brand'
    | '/category/$category/brand/$brand/item/$itemid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/category/$category'
    | '/category/$category/brand/$brand'
    | '/category/$category/brand/$brand/item/$itemid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/category/$category'
    | '/category_/$category/brand/$brand'
    | '/category_/$category/brand_/$brand/item/$itemid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  CategoryCategoryBrandBrandRoute: typeof CategoryCategoryBrandBrandRoute
  CategoryCategoryBrandBrandItemItemidRoute: typeof CategoryCategoryBrandBrandItemItemidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category_/$category/brand/$brand': {
      id: '/category_/$category/brand/$brand'
      path: '/category/$category/brand/$brand'
      fullPath: '/category/$category/brand/$brand'
      preLoaderRoute: typeof CategoryCategoryBrandBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category_/$category/brand_/$brand/item/$itemid': {
      id: '/category_/$category/brand_/$brand/item/$itemid'
      path: '/category/$category/brand/$brand/item/$itemid'
      fullPath: '/category/$category/brand/$brand/item/$itemid'
      preLoaderRoute: typeof CategoryCategoryBrandBrandItemItemidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  CategoryCategoryBrandBrandRoute: CategoryCategoryBrandBrandRoute,
  CategoryCategoryBrandBrandItemItemidRoute:
    CategoryCategoryBrandBrandItemItemidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
