/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BackendHealthRouteImport } from './routes/backend-health'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as ApiBrandsRouteImport } from './routes/api/brands'
import { Route as ApiProductsProductIdRouteImport } from './routes/api/products/$productId'
import { Route as ApiJobsScrapeRunsRouteImport } from './routes/api/jobs/scrape-runs'
import { Route as ApiJobsSchedulersRouteImport } from './routes/api/jobs/schedulers'
import { Route as CategoryCategoryBrandBrandRouteImport } from './routes/category_.$category.brand.$brand'
import { Route as ApiBrandsBrandIdProductsRouteImport } from './routes/api/brands/$brandId/products'
import { Route as ApiJobsScrapeBrandBrandIdRouteImport } from './routes/api/jobs/scrape/brand/$brandId'
import { Route as CategoryCategoryBrandBrandItemItemidRouteImport } from './routes/category_/$category/brand_/$brand/item/$itemid'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendHealthRoute = BackendHealthRouteImport.update({
  id: '/backend-health',
  path: '/backend-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandsRoute = ApiBrandsRouteImport.update({
  id: '/api/brands',
  path: '/api/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsProductIdRoute = ApiProductsProductIdRouteImport.update({
  id: '/api/products/$productId',
  path: '/api/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsScrapeRunsRoute = ApiJobsScrapeRunsRouteImport.update({
  id: '/api/jobs/scrape-runs',
  path: '/api/jobs/scrape-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsSchedulersRoute = ApiJobsSchedulersRouteImport.update({
  id: '/api/jobs/schedulers',
  path: '/api/jobs/schedulers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryBrandBrandRoute =
  CategoryCategoryBrandBrandRouteImport.update({
    id: '/category_/$category/brand/$brand',
    path: '/category/$category/brand/$brand',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBrandsBrandIdProductsRoute =
  ApiBrandsBrandIdProductsRouteImport.update({
    id: '/$brandId/products',
    path: '/$brandId/products',
    getParentRoute: () => ApiBrandsRoute,
  } as any)
const ApiJobsScrapeBrandBrandIdRoute =
  ApiJobsScrapeBrandBrandIdRouteImport.update({
    id: '/api/jobs/scrape/brand/$brandId',
    path: '/api/jobs/scrape/brand/$brandId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryCategoryBrandBrandItemItemidRoute =
  CategoryCategoryBrandBrandItemItemidRouteImport.update({
    id: '/category_/$category/brand_/$brand/item/$itemid',
    path: '/category/$category/brand/$brand/item/$itemid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backend-health': typeof BackendHealthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/api/jobs/schedulers': typeof ApiJobsSchedulersRoute
  '/api/jobs/scrape-runs': typeof ApiJobsScrapeRunsRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/brands/$brandId/products': typeof ApiBrandsBrandIdProductsRoute
  '/category/$category/brand/$brand': typeof CategoryCategoryBrandBrandRoute
  '/api/jobs/scrape/brand/$brandId': typeof ApiJobsScrapeBrandBrandIdRoute
  '/category/$category/brand/$brand/item/$itemid': typeof CategoryCategoryBrandBrandItemItemidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backend-health': typeof BackendHealthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/api/jobs/schedulers': typeof ApiJobsSchedulersRoute
  '/api/jobs/scrape-runs': typeof ApiJobsScrapeRunsRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/brands/$brandId/products': typeof ApiBrandsBrandIdProductsRoute
  '/category/$category/brand/$brand': typeof CategoryCategoryBrandBrandRoute
  '/api/jobs/scrape/brand/$brandId': typeof ApiJobsScrapeBrandBrandIdRoute
  '/category/$category/brand/$brand/item/$itemid': typeof CategoryCategoryBrandBrandItemItemidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backend-health': typeof BackendHealthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/api/jobs/schedulers': typeof ApiJobsSchedulersRoute
  '/api/jobs/scrape-runs': typeof ApiJobsScrapeRunsRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/brands/$brandId/products': typeof ApiBrandsBrandIdProductsRoute
  '/category_/$category/brand/$brand': typeof CategoryCategoryBrandBrandRoute
  '/api/jobs/scrape/brand/$brandId': typeof ApiJobsScrapeBrandBrandIdRoute
  '/category_/$category/brand_/$brand/item/$itemid': typeof CategoryCategoryBrandBrandItemItemidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backend-health'
    | '/cart'
    | '/checkout'
    | '/api/brands'
    | '/category/$category'
    | '/api/jobs/schedulers'
    | '/api/jobs/scrape-runs'
    | '/api/products/$productId'
    | '/api/brands/$brandId/products'
    | '/category/$category/brand/$brand'
    | '/api/jobs/scrape/brand/$brandId'
    | '/category/$category/brand/$brand/item/$itemid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backend-health'
    | '/cart'
    | '/checkout'
    | '/api/brands'
    | '/category/$category'
    | '/api/jobs/schedulers'
    | '/api/jobs/scrape-runs'
    | '/api/products/$productId'
    | '/api/brands/$brandId/products'
    | '/category/$category/brand/$brand'
    | '/api/jobs/scrape/brand/$brandId'
    | '/category/$category/brand/$brand/item/$itemid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backend-health'
    | '/cart'
    | '/checkout'
    | '/api/brands'
    | '/category/$category'
    | '/api/jobs/schedulers'
    | '/api/jobs/scrape-runs'
    | '/api/products/$productId'
    | '/api/brands/$brandId/products'
    | '/category_/$category/brand/$brand'
    | '/api/jobs/scrape/brand/$brandId'
    | '/category_/$category/brand_/$brand/item/$itemid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BackendHealthRoute: typeof BackendHealthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ApiBrandsRoute: typeof ApiBrandsRouteWithChildren
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ApiJobsSchedulersRoute: typeof ApiJobsSchedulersRoute
  ApiJobsScrapeRunsRoute: typeof ApiJobsScrapeRunsRoute
  ApiProductsProductIdRoute: typeof ApiProductsProductIdRoute
  CategoryCategoryBrandBrandRoute: typeof CategoryCategoryBrandBrandRoute
  ApiJobsScrapeBrandBrandIdRoute: typeof ApiJobsScrapeBrandBrandIdRoute
  CategoryCategoryBrandBrandItemItemidRoute: typeof CategoryCategoryBrandBrandItemItemidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-health': {
      id: '/backend-health'
      path: '/backend-health'
      fullPath: '/backend-health'
      preLoaderRoute: typeof BackendHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brands': {
      id: '/api/brands'
      path: '/api/brands'
      fullPath: '/api/brands'
      preLoaderRoute: typeof ApiBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$productId': {
      id: '/api/products/$productId'
      path: '/api/products/$productId'
      fullPath: '/api/products/$productId'
      preLoaderRoute: typeof ApiProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/scrape-runs': {
      id: '/api/jobs/scrape-runs'
      path: '/api/jobs/scrape-runs'
      fullPath: '/api/jobs/scrape-runs'
      preLoaderRoute: typeof ApiJobsScrapeRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/schedulers': {
      id: '/api/jobs/schedulers'
      path: '/api/jobs/schedulers'
      fullPath: '/api/jobs/schedulers'
      preLoaderRoute: typeof ApiJobsSchedulersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category_/$category/brand/$brand': {
      id: '/category_/$category/brand/$brand'
      path: '/category/$category/brand/$brand'
      fullPath: '/category/$category/brand/$brand'
      preLoaderRoute: typeof CategoryCategoryBrandBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brands/$brandId/products': {
      id: '/api/brands/$brandId/products'
      path: '/$brandId/products'
      fullPath: '/api/brands/$brandId/products'
      preLoaderRoute: typeof ApiBrandsBrandIdProductsRouteImport
      parentRoute: typeof ApiBrandsRoute
    }
    '/api/jobs/scrape/brand/$brandId': {
      id: '/api/jobs/scrape/brand/$brandId'
      path: '/api/jobs/scrape/brand/$brandId'
      fullPath: '/api/jobs/scrape/brand/$brandId'
      preLoaderRoute: typeof ApiJobsScrapeBrandBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category_/$category/brand_/$brand/item/$itemid': {
      id: '/category_/$category/brand_/$brand/item/$itemid'
      path: '/category/$category/brand/$brand/item/$itemid'
      fullPath: '/category/$category/brand/$brand/item/$itemid'
      preLoaderRoute: typeof CategoryCategoryBrandBrandItemItemidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiBrandsRouteChildren {
  ApiBrandsBrandIdProductsRoute: typeof ApiBrandsBrandIdProductsRoute
}

const ApiBrandsRouteChildren: ApiBrandsRouteChildren = {
  ApiBrandsBrandIdProductsRoute: ApiBrandsBrandIdProductsRoute,
}

const ApiBrandsRouteWithChildren = ApiBrandsRoute._addFileChildren(
  ApiBrandsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BackendHealthRoute: BackendHealthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ApiBrandsRoute: ApiBrandsRouteWithChildren,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ApiJobsSchedulersRoute: ApiJobsSchedulersRoute,
  ApiJobsScrapeRunsRoute: ApiJobsScrapeRunsRoute,
  ApiProductsProductIdRoute: ApiProductsProductIdRoute,
  CategoryCategoryBrandBrandRoute: CategoryCategoryBrandBrandRoute,
  ApiJobsScrapeBrandBrandIdRoute: ApiJobsScrapeBrandBrandIdRoute,
  CategoryCategoryBrandBrandItemItemidRoute:
    CategoryCategoryBrandBrandItemItemidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
